#include "stm32f10x.h"          

void TIM2_Init(void)
{
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN; 
	RCC->APB2ENR |= RCC_APB2ENR_IOPAEN;   
	
	GPIOA->CRL &= ~GPIO_CRL_CNF0;  /* PA0 */  
	GPIOA->CRL |= GPIO_CRL_CNF0_1;
	
	GPIOA->CRL &= ~GPIO_CRL_MODE0;
	GPIOA->CRL |= GPIO_CRL_MODE0;
	
	GPIOA->CRL &= ~GPIO_CRL_CNF1;  /* PA1 */  
	GPIOA->CRL |= GPIO_CRL_CNF1_1;
	
	GPIOA->CRL &= ~GPIO_CRL_MODE1;
	GPIOA->CRL |= GPIO_CRL_MODE1;
	
	GPIOA->CRL &= ~GPIO_CRL_CNF2;  /* PA2 */  
	GPIOA->CRL |= GPIO_CRL_CNF2_1;
	
	GPIOA->CRL &= ~GPIO_CRL_MODE2;
	GPIOA->CRL |= GPIO_CRL_MODE2;
	
	TIM2->PSC = 2400 - 1;
	TIM2->ARR = 0xFF;
	
	TIM2->CCR1 = 40 ; // 0 до 255;
	TIM2->CCR2 = 30 ; // 0 до 255;	
	TIM2->CCR3 = 50 ; // 0 до 255;	

	TIM2->CCMR1 |= TIM_CCMR1_OC1M_0 | TIM_CCMR1_OC1M_1 | TIM_CCMR1_OC1M_2; //CH1
	TIM2->CCER |= TIM_CCER_CC1E; 
	TIM2->CCER &= ~TIM_CCER_CC1P; 
	
	TIM2->CCMR1 |= TIM_CCMR1_OC2M_0 | TIM_CCMR1_OC2M_1 | TIM_CCMR1_OC2M_2; //CH2
	TIM2->CCER |= TIM_CCER_CC2E; // on CH2
	TIM2->CCER &= ~TIM_CCER_CC2P; 
	
	TIM2->CCMR2 |= TIM_CCMR2_OC3M_0 | TIM_CCMR2_OC3M_1 | TIM_CCMR2_OC3M_2; //CH3
	TIM2->CCER |= TIM_CCER_CC3E; // on CH2
	TIM2->CCER &= ~TIM_CCER_CC3P; 
	
	
	TIM2->CR1 &= ~TIM_CR1_DIR;
	TIM2->CR1 |= TIM_CR1_CEN;
}
	



int main()
{

		TIM2_Init();
				
		while(1)
		{
		
		
		}
	
	
}